### ISSUE TITLE
dom-delegator events do not work

### ISSUE THREAD

**Issue by chrisinajar** [bendrucker/thermometer#1]
The following mvc code throws an error. If you test this within the repository it works fine, it has to do with npm...

```bash
npm i dover virtual-dom thermometer value-event dispatch-event
```

```js
var h = require('virtual-dom/h');
var thermometer = require('thermometer');
var clickEvent = require('value-event/click');
var dispatchEvent = require('dispatch-event');
var Dover = require('dover');

Component.render = function (state) {
  return h('div', {
    'ev-click': clickEvent(state.channels.doThing)
  });
};

thermometer.createComponent(Component, null, function (state, dom, done) {
  dispatchEvent(dom, 'click', {button: 1});
});

function Component (data) {
  return Dover({
    channels: {
      doThing: doThing
    }
  });
}

function doThing (state) {
}
```

throws

```
$ node test.js 
/projects/thermo_test/node_modules/thermometer/node_modules/dom-delegator/dom-delegator.js:172
            HANDLER_STORE(handler).func(ev)
                                   ^

TypeError: HANDLER_STORE(...).func is not a function
    at /projects/thermo_test/node_modules/thermometer/node_modules/dom-delegator/dom-delegator.js:172:36
    at Array.forEach (native)
    at callListeners (/projects/thermo_test/node_modules/thermometer/node_modules/dom-delegator/dom-delegator.js:166:14)
    at findAndInvokeListeners (/projects/thermo_test/node_modules/thermometer/node_modules/dom-delegator/dom-delegator.js:137:9)
    at handler (/projects/thermo_test/node_modules/thermometer/node_modules/dom-delegator/dom-delegator.js:127:9)
    at /projects/thermo_test/node_modules/thermometer/node_modules/global/node_modules/min-document/event/dispatch-event.js:21:17
    at Array.forEach (native)
    at DOMElement.dispatchEvent (/projects/thermo_test/node_modules/thermometer/node_modules/global/node_modules/min-document/event/dispatch-event.js:18:26)
    at DOMElement.dispatchEvent (/projects/thermo_test/node_modules/thermometer/node_modules/global/node_modules/min-document/event/dispatch-event.js:29:25)
    at DOMElement.dispatchEvent (/projects/thermo_test/node_modules/thermometer/node_modules/global/node_modules/min-document/event/dispatch-event.js:29:25)
```

**Comment by bendrucker** [comment]
What npm version?

**Comment by chrisinajar** [comment]
```
virtual-dom@2.1.1 node_modules/virtual-dom
dispatch-event@1.0.0 node_modules/dispatch-event
value-event@5.1.0 node_modules/value-event
dover@1.2.0 node_modules/dover
thermometer@1.3.4 node_modules/thermometer
```

**Comment by chrisinajar** [comment]
I tried `npm link` locally and removed the dom delegator dependency and initialization and tried moving that into the test file, it didn't help. It seems like wherever the loop is initialized matters more than where the delegator is, it appears to be a bit of a red herring.

**Comment by bendrucker** [comment]
I mean the actual `npm -v`. `npm link` can actually break things. You need the deduping in `npm@3` for the DOM delegators to be the same.

**Comment by chrisinajar** [comment]
`2.14.3` updating now

**Comment by chrisinajar** [comment]
It works! I'm bad...

**Comment by bendrucker** [comment]
Haha all good. If you can come up w/ any ideas on how to throw when this happens I'd implement it, just never figured it out myself.
